from typing import Protocol, Any

from src.ui.views.base_view import BaseView


class ProcessView(BaseView, Protocol):
    def reset_view(self) -> None: ...
    def set_status(self, message: str) -> None: ...
    def load_jobs(self, jobs: list[Any]) -> None: ...
    def update_job_status(self, row_id: int, status: str, ticket_id: str | None, error: str | None, ) -> None: ...
    def show_completed(self, message: str) -> None: ...
    