from typing import Protocol

class SettingsView(Protocol):
    def get_report_user(self) -> str: ...
    def get_job_group(self) -> str: ...
    def set_report_user(self, value: str) -> None: ...
    def set_job_group(self, value: str) -> None: ...