from typing import Protocol

from src.ui.views.base_view import BaseView

class UploadView(BaseView, Protocol):
    def show_selected_file(self, file_name: str) -> None: ...
    def clear_selected_file(self) -> None: ...
    def show_excel_loaded(self, total_jobs: int) -> None: ...